apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-shared-vol-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-pv
  volumeMode: Filesystem
  volumeName: my-shared-vol-pv
  resources:
    requests:
      storage: 10Gi
