apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: atlassian-cluster
  region: us-east-1

managedNodeGroups:
  - name: appNodes
    instanceType: m5.large
    desiredCapacity: 2
    ssh: # enable SSH using SSM
      enableSsm: true
