apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucketdata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-pv
  volumeMode: Filesystem
  volumeName: bitbucketdata
  resources:
    requests:
      storage: 20Gi
